CREATE TABLE Libraries (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT LibraryNameUnique UNIQUE (Name)
);

CREATE TABLE Authors (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL
);

CREATE TABLE Books (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,

    CONSTRAINT BookIsbnUnique UNIQUE (ISBN),
    CONSTRAINT BookIsbnFormat CHECK (ISBN ~ '^([0-9]{9}[0-9X]|[0-9]{13})$')
);

CREATE TABLE BookAuthor (
    BookId INT NOT NULL,
    AuthorId INT NOT NULL,
    Position SMALLINT NOT NULL DEFAULT 1,

    PRIMARY KEY (BookId, AuthorId),
    FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE CASCADE,
    FOREIGN KEY (AuthorId) REFERENCES Authors(Id) ON DELETE RESTRICT
);

CREATE TABLE BookCopy (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Barcode VARCHAR(50) NOT NULL,
    AddedAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    BookId INT NOT NULL,
    LibraryId INT NOT NULL,

    CONSTRAINT BookCopyBarcodeUnique UNIQUE (Barcode),
    FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE RESTRICT,
    FOREIGN KEY (LibraryId) REFERENCES Libraries(Id) ON DELETE CASCADE
);

CREATE TABLE Users (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE Members (
    UserId INT NOT NULL,
    LibraryId INT NOT NULL,
    JoinedAt TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (UserId, LibraryId),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (LibraryId) REFERENCES Libraries(Id) ON DELETE CASCADE
);

CREATE TABLE Loans (
    Id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LoanedAt TIMESTAMPTZ NOT NULL DEFAULT now(),
    DueAt TIMESTAMPTZ NOT NULL,
    ReturnedAt TIMESTAMPTZ,
    BookCopyId INT NOT NULL,
    UserId INT NOT NULL,

    CONSTRAINT LoanDueAfterLoaned CHECK (DueAt > LoanedAt),
    CONSTRAINT LoanReturnedAfterLoaned CHECK (ReturnedAt IS NULL OR ReturnedAt >= LoanedAt),
    FOREIGN KEY (BookCopyId) REFERENCES BookCopy(Id) ON DELETE RESTRICT,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE RESTRICT
);
